name: voice_message_package
description: Flutter package to play voice message in chats with playback speed x1/x2.
version: 0.0.4
homepage: https://github.com/mehranshoqi/voice_message_player

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.20.0
  just_audio: ^0.9.20
  sizer: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


